database:
  driver: mysql
  dsn: root:password@tcp(localhost:3306)/token_tracker?charset=utf8mb4&parseTime=True&loc=Local
  max_open: 10
  max_idle: 5
  life_time: 30

chains:
  - name: sepolia
    id: 11155111
    rpc_url: https://sepolia.infura.io/v3/xxxx
    contract_addr: "0x????"
    start_block: 4000000
  
  - name: base-sepolia
    id: 84532
    rpc_url: https://base-sepolia.infura.io/v3/xxxx
    contract_addr: "0x????"
    start_block: 1000000

processor:
  block_batch_size: 1000
  reorg_threshold: 6
  check_interval: 30

points:
  calculation_interval: 60  # 每小时计算一次
  rate: 0.05  # 积分计算比例